### ISSUE TITLE
Insights for POWERPLAY season not available

### ISSUE THREAD

**Issue by chaosbuster** [the-orange-alliance/the-orange-alliance#85]
The data and charts within the Insights section are not valid and / or populating for the POWERPLAY season.

**Steps to reproduce the issue**
1. Go to Menu
2. Click on 'Insights'
3. The page selection defaults to '2022/23 PowerPlay' for Season and 'All Regions' for Region.
4. No data is shown.  'Season Specific' charts are not displayed at all. Overall charts displayed with no data are:
- Average Match Scores
- Average Win Margin
- Average Match Penalties

**Screenshots**
![image](https://user-images.githubusercontent.com/5160817/210639433-ce9cba50-9460-4653-a70f-23ba4f7eeb35.png)

**Expected behavior**
1. Charts for overall match play displaying data for completed events that have been uploaded.
2. Charts specific for the season displaying season specific data for completed events that have been uploaded.

Recommended charts for POWERPLAY season in the 'Season Specific' section:
- Autonomous # of Cones Scored (Terminal, Ground Junction, Low Junction, Medium Junction, High Junction)
- Autonomous Parking (In Terminal, Navigated, Navigated with Custom Sleeve)
- Teleop # of Cones Scored (Terminal, Ground Junction, Low Junction, Medium Junction, High Junction)
- End Game Junction Ownership (Junctions Owned by Cones, Junctions Owned by Beacons)
- End Game Completed Circuit
- End Game Parking (Terminal)

**Environments**
- Operating System Windows 11 Home (22H2)
- Browser:   Chrome 108.0.5359.125

**Comment by Nate2019** [comment]
Insights have since been aded to the site - Issue can be closed
